create database blog;
use blog;
CREATE TABLE MST_CATEGORY(
	CATEGORY_CODE CHAR(2) NOT NULL,
	CATEGORY_NAME NVARCHAR(255) NOT NULL,
	URL NVARCHAR(255) NOT NULL,
	SUBDIR NVARCHAR(255) NOT NULL,
	ISHOME BOOLEAN DEFAULT FALSE NOT NULL,
	ISDELETED BOOLEAN DEFAULT FALSE NOT NULL,
	SEQUENCE INT NOT NULL,
	
	PRIMARY KEY(CATEGORY_CODE)
);
CREATE TABLE TSN_POST(
	IDX INT NOT NULL AUTO_INCREMENT,
	CATEGORY_CODE CHAR(2) NOT NULL,
	LOCATION VARCHAR(2048) NOT NULL COMMENT 'URL Address',
	CHANGEFREG INT DEFAULT 5 NOT NULL, 
	CREATEDATED DATETIME DEFAULT now() NOT NULL, 
	LAST_UPDATED DATETIME DEFAULT now() NOT NULL,
	PRIORITY INT DEFAULT 5 NOT NULL,
	TITLE NVARCHAR(2048) NOT NULL, 
	FILEPATH VARCHAR(2048) NULL, 
	GUID VARCHAR(255) DEFAULT uuid() NOT NULL, 
	IMAGE LONGBLOB NULL, 
	SUMMARY NVARCHAR(4096) NOT NULL,
	ISDELETED BOOLEAN DEFAULT FALSE NOT NULL,
	
	PRIMARY KEY(IDX),
	FOREIGN KEY(CATEGORY_CODE) REFERENCES MST_CATEGORY(CATEGORY_CODE)
);

CREATE TABLE HSR_POST(
	IDX INT NOT NULL AUTO_INCREMENT,
	ACTION_DATE DATETIME DEFAULT NOW() NOT NULL,
	ACTION_TYPE CHAR(1) NOT NULL,
	OIDX INT NULL,
	CATEGORY_CODE CHAR(2) NULL,
	LOCATION VARCHAR(2048) NULL,
	CHANGEFREG INT NULL, 
	CREATEDATED DATETIME NULL, 
	LAST_UPDATED DATETIME NULL,
	PRIORITY INT NULL,
	TITLE NVARCHAR(2048) NULL, 
	FILEPATH VARCHAR(2048) NULL, 
	GUID VARCHAR(255) NULL, 
	IMAGE LONGBLOB NULL, 
	SUMMARY NVARCHAR(4096) NULL,
	ISDELETED BOOLEAN NULL,
	
	PRIMARY KEY(IDX)
);




INSERT INTO MST_CATEGORY VALUES("01", N'홈', '/', '/', TRUE, FALSE, 1);
INSERT INTO MST_CATEGORY VALUES("02", N'개발일기', '/DialyList.html', '/Dialy/',FALSE, FALSE, 2);
INSERT INTO MST_CATEGORY VALUES("03", N'개발경험', '/ExperienceList.html', '/Experience/', FALSE, FALSE, 3);
INSERT INTO MST_CATEGORY VALUES("04", N'한국생활', '/KoreanLifeList.html', '/KoreanLife/', FALSE, FALSE, 5);
INSERT INTO MST_CATEGORY VALUES("05", N'일본생활', '/JapanLifeList.html', '/JapanLife/', FALSE, FALSE, 4);
INSERT INTO MST_CATEGORY VALUES("06", N'코딩노트', '/CodingNoteList.html', '/CodingNote/', FALSE, FALSE, 6);
INSERT INTO MST_CATEGORY VALUES("07", N'즐겨찾기', '/FavoritesList.html', '/Favorites/', FALSE, FALSE, 7);


delimiter //

CREATE TRIGGER TSN_POST_AFTER_MODIFY
AFTER UPDATE ON TSN_POST
	FOR EACH ROW
BEGIN
	INSERT INTO HSR_POST(
		ACTION_TYPE,
		OIDX,
		CATEGORY_CODE,
		LOCATION,
		CHANGEFREG,
		CREATEDATED,
		LAST_UPDATED,
		PRIORITY,
		TITLE,
		FILEPATH,
		GUID,
		IMAGE,
		SUMMARY,
		ISDELETED
	) VALUES (
		'M',
		OLD.IDX,
		OLD.CATEGORY_CODE,
		OLD.LOCATION,
		OLD.CHANGEFREG,
		OLD.CREATEDATED,
		OLD.LAST_UPDATED,
		OLD.PRIORITY,
		OLD.TITLE,
		OLD.FILEPATH,
		OLD.GUID,
		OLD.IMAGE,
		OLD.SUMMARY,
		OLD.ISDELETED
	);
END;
//
CREATE TRIGGER TSN_POST_BEFORE_DELETE
BEFORE DELETE ON TSN_POST
	FOR EACH ROW
BEGIN
	INSERT INTO HSR_POST(
		ACTION_TYPE,
		OIDX,
		CATEGORY_CODE,
		LOCATION,
		CHANGEFREG,
		CREATEDATED,
		LAST_UPDATED,
		PRIORITY,
		TITLE,
		FILEPATH,
		GUID,
		IMAGE,
		SUMMARY,
		ISDELETED
	) VALUES (
		'D',
		OLD.IDX,
		OLD.CATEGORY_CODE,
		OLD.LOCATION,
		OLD.CHANGEFREG,
		OLD.CREATEDATED,
		OLD.LAST_UPDATED,
		OLD.PRIORITY,
		OLD.TITLE,
		OLD.FILEPATH,
		OLD.GUID,
		OLD.IMAGE,
		OLD.SUMMARY,
		OLD.ISDELETED
	);
END;
//
delimiter ;